### ISSUE TITLE
Shared memory for containers

### ISSUE THREAD

**Issue by stereoit** [appc/spec#100]
Hello, would it be possible to specify some IPC mechanisims for containers? Something like --ipc switch to docker does. Basically I need more than one container to have access to a shared memory.

**Comment by pablochacin** [comment]
Hi. I'm curious about your use case. Why do you need containers to share memory? I've always considered the idea of share-nothing for containers, to give more flexibility when deploying them.

**Comment by jonboulle** [comment]
Alternatively, you could run multiple apps within a single container, and they would share an IPC namespace.

**Comment by stereoit** [comment]
I also seeked complete isolation from containers, however appliance is a good use case. We have a box with high perfomance computing card, this card is represented as a special device and is using DMA for high memory bandwidth (processing 100gb/s of traffic), client applications (running and developed in a container) need to have low latency and high performance access to this area. 

Since our engine and client app is developed separately, there should be isolation between those two. I need to guarantee isolation per app (processes, memory and such), otherwise badly written client software can affect our engine.

**Comment by jonboulle** [comment]
@stereoit similar to my comment in #99 , I am not really sure this should go directly in the spec since it is a bit platform specific. 

I think what I would want is to see an example of this working in an implementation of the spec (either Rocket, for example, or an alternative implementation), and then consider "promoting" it to the spec after feeling that out and giving it some more thought. What do you think?

**Comment by stereoit** [comment]
Given the fact this was also implemented quite recently in docker I think
the proposed solution is OK. Of course it would be cool to see this in rkt
implemented. While reading the Container Runtime Manifest Schema I did
notice it supports multiple apps within one container, which would probably
somehow worked fine for me as well, but this is completely new to me and I
did not find any more documentaion or blogposts on this.

**Comment by pablochacin** [comment]
@jonboulle  +1000 on  your suggestion to explore first to what extend a new requirement can be solved with the current spec, possibly experimenting with alternative implementation, than cluttering the spec with any possible use case. I hope the group can adhere to this philosophy.

**Comment by jonboulle** [comment]
I am going to close this for now. @stereoit please feel free to file a feature request against Rocket if you would like to see this there. Also, both this project and rocket are still very young, so documentation and blogposts are a bit sparse, but we're hard at work improving that - any contributions or suggestions for specific docs would be welcome!
