### ISSUE TITLE
CRM: allow overriding/extending app environment

### ISSUE THREAD

**Issue by wereHamster** [appc/spec#104]
It would be convenient to be able to create a single image and then use it in different environments (production, staging, qa, ...). This is currently not possible because there is no way to parametrize the executables which are running inside a container. The executable, its arguments, and environment variables are defined in the ImageManifest and the CRM can not override those.

I propose adding a new field to CRM `apps.app` with the name `environment` and value same as ImageManifest `app.environment`. The executor would then merge the CRM app environment into the IM app environment (allowing the former to override the environment of the later).

**Comment by wereHamster** [comment]
Actually, it might be useful to have a more strictly defined way to parametrize the executable, similar to how mount points are defined. A set of inputs (parameters) which must be supplied by the outside (executor, user) and without which the executable can not function.

This would make it possible to:

  - Prompt the user for input while trying to create a container (rkt run ..).
  - Validate the container before actually executing the apps within.
  - Automatically generate forms in a web based container management UI.

**Comment by jonboulle** [comment]
@wereHamster I think this is covered by #84 (at least what I had in mind), do you mind if we close this out and move the discussion there?

**Comment by jonboulle** [comment]
@wereHamster I updated the OP of #84 to include mention of environment

> Actually, it might be useful to have a more strictly defined way to parametrize the executable, similar to how mount points are defined. A set of inputs (parameters) which must be supplied by the outside (executor, user) and without which the executable can not function.

I am not really sure what you are getting at here. The executor (and user) can provide parameters to applications through environment variables (and the metadata service), is that not sufficient? Can you give me an example of parameters "without which the executable can not function"?

**Comment by jonboulle** [comment]
I believe this has been adequately resolved by https://github.com/appc/spec/commit/9aafd97bcebd31d7f82b7f04fb1d2ce4661ec3b8
