### ISSUE TITLE
spec: signing clarification

### ISSUE THREAD

**Issue by matwey** [appc/spec#105]
The spec says:

> Image archives MUST be a tar formatted file. The image may be optionally compressed with gzip, bzip2, or xz. After compression, images may also be encrypted with AES symmetric encryption.

> ```
tar cvf reduce-worker.tar app rootfs
gpg --output reduce-worker.sig --detach-sig reduce-worker.tar
gzip reduce-worker.tar -c > reduce-worker.aci
```

At the same time, there is no mention of the second line command. Putting the signature on tar. Is it optional or mandatory?

**Comment by philips** [comment]
On Sat, Jan 10, 2015 at 1:29 AM, Matwey V. Kornilov <
notifications@github.com> wrote:

> Putting the signature on tar. Is it optional or mandatory?


I don't think I understand the question. Are you asking what should be done
with detached signature after it is generated?

**Comment by matwey** [comment]
Yes, It can be put in that way. What should be done with signature file?

**Comment by jonboulle** [comment]
Actually I agree with @matwey that it is not exactly clear from the current wording whether signing+verification of images is mandatory or not - we should be explicit about that, since we are for the compression/encryption.

**Comment by kelseyhightower** [comment]
@matwey Currently in rocket we have enabled signature validation by default and maybe the spec should provide clarification.

@matwey Here is what just landed on master: https://github.com/coreos/rocket/blob/master/Documentation/signing-and-verification-guide.md

**Comment by jonboulle** [comment]
Attempted to clear this up in #156

**Comment by jonboulle** [comment]
This should be clear now on master.
