### ISSUE TITLE
spec: dependencies details > fs paths

### ISSUE THREAD

**Issue by frntn** [appc/spec#107]
I know we must think *simplicity*, but while thinking of real life use cases, I though we'll end up to be able to specify the **from** and **to** between dependencies ? 

**Image Manifest sample** (example)
```json
...
        "dependencies": [
        {
            "app": "example.com/reduce-worker-base",
            "imageID": "sha512-...",
            "srcPath": "rootfs/opt/mylib/",
            "dstPath" : "rootfs/opt/myapp/vendors/reduce-worker-base",
            "labels": [
                {
                    "name": "os",
                    "value": "linux"
                },
                {
                    "name": "env",
                    "value": "canary"
                }
            ]
        }
    ],
...
```

What do you think ?

**Comment by jonboulle** [comment]
Hrm, we toyed with this idea in the past actually - every dependency had a "mountPoint" specified, which is where it would be rooted within the resultant layout. I am not sure it necessarily makes things easier, though - or to put it another way, am not sure the use case justifies the added complexity. I think I would rather wait until we see more use of dependencies before making a change like this.

**Comment by frntn** [comment]
In terms of implementation it adds a very little complexity yes.
But in terms of usability it stays as simple (these fields would be OPTIONNAL) with more flexibility.

Don't you think ?

**Comment by philips** [comment]
@frntn what are some example use cases? I see what you would like to do but I can't help but think that there has to be a better way to accomplish the end goal.

**Comment by jonboulle** [comment]
I am going to close this out due to inactivity (and we have put a fair amount of effort into clarifying the dependencies mechanism in the last few releases). Please re-open if you'd like to discuss further.
