### ISSUE TITLE
spec: missing expected behaviour

### ISSUE THREAD

**Issue by frntn** [appc/spec#109]
This is more like a **general purpose issue** to mention that the specs lacks of informations on expected behaviours. While reading the spec, many times I thought "how would I handle it with this particular use case if I had to implement it ?"

For example for `pathWhitelist` : 

- does the runtime (container executor) juste filter out the allowed paths from dependency acis, or will it raise an error if some dependency container contains files outside the allowed paths ?
- **"This field is only required if the app has dependencies and you wish to remove files from the rootfs before running the container"** => Ok i now have my answer (files from dependency container but outside the folder path are just dropped) but will it raise an error if the field is missing ? (does "required" means "mandatory" here, not sure..)
- **"an empty value means that all files in this image and any dependencies will be available in the rootfs."** => here again : what about a missing value ?

**Comment by jonboulle** [comment]
> does the runtime (container executor) juste filter out the allowed paths from dependency acis, or will it raise an error if some dependency container contains files outside the allowed paths ?

It filters; what's in the pathWhitelist is all that ends up in the resolved layout

> "This field is only required if the app has dependencies and you wish to remove files from the rootfs before running the container" => Ok i now have my answer (files from dependency container but outside the folder path are just dropped) but will it raise an error if the field is missing ? (does "required" means "mandatory" here, not sure..)

No, "required" here means "necessary if you wish to accomplish this". The pathWhitelist field is always an _optional_ part of the manifest, but if you want to filter paths, you need to include it. Any ideas how we can subtly tweak this to make that clearer?

> "an empty value means that all files in this image and any dependencies will be available in the rootfs." => here again : what about a missing value ?

A missing value means the field is not defined, does that make sense?

**Comment by frntn** [comment]
> No, "required" here means "necessary if you wish to accomplish this". The pathWhitelist field is always an optional part of the manifest, but if you want to filter paths, you need to include it. Any ideas how we can subtly tweak this to make that clearer?

Like in RFCs I would use keywords (https://www.ietf.org/rfc/rfc2119.txt) through the whole document.
In this example the sentence could be : 
```
The pathWhitelist is an OPTIONAL field. 
You MUST add it to filter in allowed paths from the app dependent rootfs to final container rootfs. 
An empty value MUST be considered as a missing field so no files from rootfs dependencies will be filtered out"
```

**Comment by kelseyhightower** [comment]
@frntn I like the use of the RFC keywords.

**Comment by kelseyhightower** [comment]
@frntn Can you put together a PR that helps clarify things using the RFC keywords as suggested? Thanks.

**Comment by jonboulle** [comment]
> The pathWhitelist is an OPTIONAL field. 
> You MUST add it to filter in allowed paths from the app dependent rootfs to final container rootfs. 

Frankly I find this even more confusing, because it's a conditional MUST (which the RFC does not really describe) but the "if" is not particularly prominent.

How about:

> pathWhitelist MAY be included, in which case ...
> An empty pathWhitelist is equivalent to it not being present.

**Comment by frntn** [comment]
@jonboulle I'm ok this : 

> pathWhitelist MAY be included to filter in allowed paths from the app dependent rootfs to final container rootfs.
> An empty pathWhitelist is equivalent to it not being present.

**Comment by jonboulle** [comment]
Missed this when closing #122. This wording has been tweaked quite a bit recently. Please let us know if it's still unclear.
