### ISSUE TITLE
Spec first read feedback

### ISSUE THREAD

**Issue by philips** [appc/spec#12]
_From @thockin on December 2, 2014 2:25_

Collected notes as I read through.  Sorry for the length.  If any of these become worth discussing, we can fork to different topics.

This changes the established naming from what Docker calls a container to what Kubernetes calls a pod.  I think that changing the meaning of "container" at this point might be detrimental to the overall comprehension of the system.  I would propose to keep container to mean what you call app-container and define a different word for a set of containers.

Example use case talks about "puts them into its local on-disk cache" and "extracts two copies".  This sets off immediate alarm bells for me - disk IO is the single most contended resource, in our experience.  To be successful, this spec really must be implementable with a minimum of disk IO.  For example, I should be able to mount a pre-built cache of images and satisfy container run requests.  That's not to say that disk IO can not satisfy the spec, but it must not be a requirement.

SIGTERM should be just one kind of termination signal

Files in an images "must maintain all of their original properties" - can this include capabilities?

One thing Docker does well is differentiate WHAT to run from HOW to run it.  Does this address that idea?  There's some overlap in lifecycle stuff, but some other things like resources are clearly dependent on how a container will be used.  How about command line flags?  Being able to take a pre-built container, such as ubuntu, and run things in it without creating and pushing a new container is powerful.

That rkt is not a daemon is very similar to what we were pushing with lmctfy.  However, there are things that (currently) are hard to do without any daemon - an example we run up against is prioritized OOM handling.  This spec should carefully consider the strata of the overall system and how some things cross between them.

Volumes are under-specified.  Can I mount them at different places in each app?  Can I not mount them in some apps?

Network: Does each APP get a network or each container?  I'm a bit unclear on the naming and distinction between container and app.  Does rkt provide "out of the box" network at all?  Docker's got this part pretty well, even if it is terribly slow.

AC_APP_NAME - what does "the entrypoint that this process was defined from" mean?

Isolators: Who do I have to beg to NOT reinvent this, and instead use something derived from LMCTFY?  We have captured YEARS of development in LMCTFY's concepts.  For example, exposing CPU shares is a mess.  If there are things about LMCTFY's structures that don't work, let's iron those out instead..

You say "if the ACE is looking for example.com/reduce-worker-1.0.0 it will request: https://example.com/reduce-worker?ac-discovery=1".  What principle lead to some piece of software knowing where to split that string?

You make some remark about /etc/hosts being assumed present and parsed by libc.  Does this mean you won't provide /etc/hosts, /etc/resolv.conf, etc?  That seems like a bad idea.

 meanYou say config-drives "make assumptions about filesystems which are not appropriate for all environments" - can you explain?  Why is it not sufficient to say that config can also be found in a volume, if the user so prefers?  The host environment should be able to provide that.

"name": "example.com/reduce-worker-1.0.0" - why is version just jammed in there? Or are you trying to say "version is opaque" and if you want it, you have to embed it in the name?

Can we define user and group as name strings, not as numerics (and why are they string numbers?)

Why do you need a private network flag?  This hasn't really answered how networking will work.  This has been a huge PITA with Docker because EVERYONE has a different idea of what they want in networks.  You can NOT support flags for all of them, so I'd argue to support none of them and instead define that as a plugin, and ship some examples of network plugins but leave it open.

_Copied from original issue: coreos/rocket#151_

**Comment by jonboulle** [comment]
I am pretty confident that almost everything raised here has been addressed in the spec, with the following exceptions still open for discussion:
- Different kinds of termination signals: #290
- /etc/hosts, /etc/resolv.conf, etc: #144 
- users/groups: #231
