### ISSUE TITLE
SPEC: propose erroring on overlapping files in tar

### ISSUE THREAD

**Issue by philips** [appc/spec#146]
Tar has this pretty sad property that dentries can appear multiple times in the same file. I was thinking it would be rather pragmatic to just say this is always an error and advise executors to reject such files.

Thoughts?

**Comment by cdaylward** [comment]
It's a great property when tar is used to actually store on tape! :)
+1 on this. My approach would be to reject any ACI that does not _strictly_ follow the format (manifest must be a regular file, rootfs must be a directory, error on any extraneous top-level files).

**Comment by jonboulle** [comment]
+1, we have been dancing a little around the fact that the tar stuff is slightly underspecified, this is as good a place to start as any for being stricter/clearer.

**Comment by jonboulle** [comment]
Fixed by #186, thanks.
