### ISSUE TITLE
app-container: add a library to convert docker image to ACI

### ISSUE THREAD

**Issue by philips** [appc/spec#15]
_From @philips on December 1, 2014 23:52_

It would be interesting to make the app-container spec inter-op with docker registries. The pkg should have an entry point where the user can start with a docker registry URL and tag (e.g. quay.io/coreos/etcd:v0.4.6) then:

- [ ] Talk to the registry API and fetch the layers
- [ ] Download the layers and convert them to images (How do we label these images? name={url},layer={layerid})
- [ ] For the root image use the version as the final tag

_Copied from original issue: coreos/rocket#142_

**Comment by iaguis** [comment]
I started playing with this idea in [endocode/docker2aci](https://github.com/endocode/docker2aci)

Right now it talks to a docker registry, fetches the layers and creates an ACI for each layer, optinally importing them to the CAS. This is an example manifest:

```
{
   "acKind" : "ImageManifest",
   "labels" : [
      {
         "name" : "layer",
         "value" : "c5f34efc44466ec7abb9a68af20d2f876ea691095747e7e5a62e890cdedadcdc"
      },
      {
         "value" : "latest",
         "name" : "version"
      },
      {
         "value" : "linux",
         "name" : "os"
      }
   ],
   "name" : "quay.io/coreos/etcd-c5f34efc44466ec7abb9a68af20d2f876ea691095747e7e5a62e890cdedadcdc",
   "acVersion" : "0.1.1",
   "dependencies" : [
      {
         "labels" : [
            {
               "value" : "linux",
               "name" : "os"
            },
            {
               "name" : "arch",
               "value" : "amd64"
            }
         ],
         "app" : "quay.io/coreos/etcd-78d63abf03b980919deaac3454a80496559da893948f427868492fa8a0d717ab"
      }
   ],
   "app" : {
      "exec" : [
         "/etcd"
      ],
      "user" : "0",
      "group" : "0"
   }
}
```

With the ACI Renderer library (coreos/rocket#297) I should be able to render these layers and run the converted image. I still haven't looked into it.

Is something like this what you had in mind?

**Comment by jonboulle** [comment]
@iaguis yeah, at a high level that looks good! I will file some issues in that repository

**Comment by jonboulle** [comment]
I am going to close this in lieu of the project [endocode/docker2aci](https://github.com/endocode/docker2aci), since this functionality likely does not belong in the spec repo anyway. Perhaps at a future date we can move to appc/docker2aci
