### ISSUE TITLE
SPEC: propose not requiring private net for metadata-svc use

### ISSUE THREAD

**Issue by eyakubovich** [appc/spec#153]
Having private networking (container having its own IP) is certainly useful for both ensuring port space isolation and ability to firewall traffic between containers. At the same time it brings a lot of complexity to existing infrastructure. For many use cases, the benefits don't outweigh the costs and it's easier to get many of the benefits of containerization while sharing the network stack with the host.

The current spec effectively disallows sharing the host network as it makes it very difficult for metadata service to identify the calling container. I propose the use of bearer token passed in via Authorization header to securely identify a container. The bearer token would be passed in to application via environment variable AC_METADATA_TOKEN.

The spec already requires the use of a custom HTTP header (Metadata-Flavor) so the burden on the users should not greatly increase.

**Comment by eyakubovich** [comment]
Additionally the ACE needs to ensure against the container changing its IP and spoofing another container. While this possible it places additional burden on the runtime.

/cc @philips @jonboulle

**Comment by jonboulle** [comment]
Seems reasonable to me. @cdaylward this also somewhat ties in to our
discussion about being less dogmatic in the text (so that the metadata
service doesn't look incredibly complex to implement, for example)
Am 18.03.2015 17:19 schrieb "Eugene Yakubovich" <notifications@github.com>:

**Comment by jonboulle** [comment]
@eyakubovich where'd you end up with your thinking on this?

**Comment by schancel** [comment]
:+1: I think this is a much better way to handle this.   Makes it easier to deal with containers that might have multiple subnets, and is more secure.  Is the plan to pass a bearer token in an ENV variable?
