### ISSUE TITLE
aci: add library for fetching and assembling dependent filesets/images

### ISSUE THREAD

**Issue by philips** [appc/spec#16]
_From @philips on December 1, 2014 23:45_

AC images can have [dependent images][fileset] however we don't have a library for finding, fetching and assembling these dependent images. 

- [x] Add a library to fetch dependent sets
- [x] Add a library that given all of the images are in the store renders the correct filesystem to disk

[fileset]: https://github.com/coreos/rocket/blob/master/app-container/SPEC.md#fileset-images

_Copied from original issue: coreos/rocket#140_

**Comment by jonboulle** [comment]
This is fixed in the spec via https://github.com/appc/spec/tree/master/pkg/acirenderer and in rkt in https://github.com/coreos/rkt/pull/661 - not sure if the latter can/should be moved here.
