### ISSUE TITLE
imageID vs imageId

### ISSUE THREAD

**Issue by benatkin** [appc/spec#167]
Neat project! I like how the format is in JSON. Just bringing this up in case it hasn't been considered: if abbreviations are added in the API, will capitalizing both letters of `ID` cause consistency issues? Would `imageId` better fit in with `acVersion`? Would using the same capitalization of `document.getElementById` in HTML, DOM, and client-side JavaScript make it easier to remember?

**Comment by philips** [comment]
@benatkin In the spec we should follow the acronym capitalization rules from Go. Lower case all of the letters in the beginning of an identifier. Upper case all of the letter if it is in the middle. 

Examples:

httpVerb
serveHTTP

It is one of those arbitrary choices so we just picked this one. Hope that makes sense! Thank you for taking a look at the project, lots of places to get involved :)
