### ISSUE TITLE
Ownership, Governance, TM, etc

### ISSUE THREAD

**Issue by philips** [appc/spec#21]
_From @mikeal on December 1, 2014 23:40_

I hate to be "that guy" but I would like to know what the plan is here in terms of ownership, governance, and the trademark, although I'm skeptical you could actually trademark "rocket" :P

The post announcing this project cited some divergences in philosophy from Docker (the project and the company). It would be good to know if this project intends to be a pure community effort or if this is just CoreOS disagreeing with Docker.

It would be great to see a contribution policy that laid out how people get involved in the project and contribute to decision making and how contentious issues like the ones that have coalesced in Docker that lead to this project would be resolved. If not it would seem like people are just trading Docker (the company) for CoreOS (the company).

_Copied from original issue: coreos/rocket#139_

**Comment by jonboulle** [comment]
We have added our first governance policy for the spec itself via #282 and are seeking to add more maintainers. I am going to close this out for now, but feel free to open issues if there are further questions.
