### ISSUE TITLE
layout validation gets confused by "manifest" and/or "rootfs" files under rootfs/

### ISSUE THREAD

**Issue by dardok** [appc/spec#236]
In experimenting with actool, I discovered that if the rootfs contains a file named "manifest" anywhere in the tree, it gets used as the image manifest for validation purposes (and will fail if its not valid JSON).  It will also incorrectly fail if there's a file named "rootfs" anywhere in the tree under rootfs/.

ValidateLayout could return "filepath.SkipDir" for RootfsDir, perhaps?  Unsure how rigorous the check under rootfs/ should be...

**Comment by iaguis** [comment]
If I'm not mistaken, we should check only the "manifest" and "rootfs/" in the root path of the layout so [using filepath.Base()](https://github.com/appc/spec/blob/80f1c924c5ca698cb15e2119aeb52245f48370ed/aci/layout.go#L63) is wrong.

#237
