### ISSUE TITLE
BuildWalker gets stuck on fifo files in rootfs

### ISSUE THREAD

**Issue by dardok** [appc/spec#238]
aci/build.go should probably not try to open os.ModeNamedPipe (or os.ModeSocket?)

**Comment by dardok** [comment]
Looks like go/tar may not be able to extract fifo types:

# rkt prepare ...
"error expanding app image: error extracting ACI: error extracting tarball: unsupported type: 54"

Investigating...

**Comment by dardok** [comment]
Its an unimplemented type in rocket/pkg/tar/tar.go.  Opening issue over there...

**Comment by jonboulle** [comment]
Is there still something that needs to be fixed in the spec code or is it just on the Rocket side?

**Comment by jonboulle** [comment]
never mind, found #240

**Comment by jonboulle** [comment]
fixed by #240
