### ISSUE TITLE
discussion: read-only app container filesystems

### ISSUE THREAD

**Issue by jonboulle** [appc/spec#245]
This is a discussion topic.

In chatting with @thockin about deploying application containers at scale, one potentially useful pattern that came up is the idea of making the filesystems in which applications execute (i.e. the container chroot) mostly read-only. Specifically, applications in containers can only write to a known part of the filesystem (e.g. a tmpfs mounted at `/home/` or some other location codified in the spec or manifest), and all of the files/directories supplied by the images are not writeable.

The obvious/major downside is that applications need to be designed and built to anticipate this restriction. However, it is generally a vastly simplifying assumption with respect to implementation of filesystem rendering and image management, largely due to the removal of the need to fiddle with copy-on-write mechanisms (all of which, at the time of writing on Linux, have various known issues/caveats). Strategies like making an entire set/repository of images available over network-mounted filesystems become very easy.

It seems somewhat plausible that this could be added to the spec in an optional fashion (as a simple parameter in the image manifest), although the semantics are then slightly unclear in terms of e.g. how read-only should be enforced.

**Comment by eyakubovich** [comment]
Well behaved apps (except pkg managers) only write to /home (/root), /run, /var, and /tmp. Maybe to /media and /mnt but that's only if they've been pointed to there. Less well behaved ones also write to /etc and /opt.

We could make /etc/, /home, /root, /run, /mnt, /media, /var, /tmp, /opt be tmpfs and copy files from aci there on startup. These directories in the aci should be mostly empty. The rest would be read-only. If  containers are meant to be ephemeral, this should work fine.

**Comment by jonboulle** [comment]
@eyakubovich if we are mounting the image read-only but then copying certain files into a bunch of additional readwrite mounts on top of that we are effectively just doing (preoptimised) COW anyway, no?

**Comment by eyakubovich** [comment]
@jonboulle It's copy on setup of stage2 (much like what rkt does now). The difference is that we're not copying /usr and friends which I'm assuming holds the majority of bits.

After thinking some more I can say that it's more than just package managers that write to /usr. A class of programs that we can call system utilities do (e.g. locale-gen). However they should run as part of image creation process and not as part of aci execution.

**Comment by alban** [comment]
In order to mount the directories ``/tmp``, ``/var`` etc. as tmpfs, the directories should exist (we cannot mount on non-existent directories). What should the executor do when the aci does not contain them? I guess we could just skip the mount when the target directory is missing. An application should not write in ``/var`` if ``/var`` is missing anyway.

prepare-app creates ``/proc``, ``/sys``, ``/dev`` etc. if they don't exist. The ``mkdir`` will fail if ``/`` is read-only. This can be changed to skip the ``mkdir`` step and to ignore the error when mounting on non-existent targets.

Should stage1 be read-only as well? ``reaper.sh`` writes to ``/rkt/status/$app`` so ``/rkt/status/`` would need to use a tmpfs as well.

**Comment by eyakubovich** [comment]
On the one hand, if the aci does not contain a directory, we can skip it under the assumption it's not required by the aci. On the other, to make it more user friendly, I wouldn't mind mkdir'ing non-existent dirs to mount over them. Obviously that's problematic to pull off if `/` is read-only.

**Comment by thockin** [comment]
You can mount / as tmpfs, then bind-mount each element of /* from the ACI
into that tmpfs.  This lets you mkdir for the stuff you say you need
according to spec.

On Thu, Mar 19, 2015 at 2:16 PM, Eugene Yakubovich <notifications@github.com
