### ISSUE TITLE
Fast container updates

### ISSUE THREAD

**Issue by vassilevsky** [appc/spec#255]
Hello :)

It's not clear for me how running containers are going to be updated as fast as possible.

Use case: a 128 MB container image running a big application. I want to add an extra call to logger — for debugging a problem that can only be reproduced in production — and deploy it. 1 file changed.

It looks like I will have to repackage the entire application, making another 128 MB file, and the runtime will have to download it entirely, unpack it all, and run.

Is there a better way? Some patching mechanism to deliver minuscule changes ASAP?

Sorry if I missed in in the specs.

**Comment by philips** [comment]
You could publish a new debug container that depends on the original container and only contains that one changed file in the rootfs. See the dependencies section of the spec: https://github.com/appc/spec/blob/master/SPEC.md#dependency-matching

I am going to close this out assuming it solves your use case, if it does not then please re-open. Thanks!

**Comment by vassilevsky** [comment]
OK! I searched the SPEC for "depend" and I can see now that information about dependencies is there. But it's scattered across the document and seems to skip the mind on the first read :)

**Comment by jonboulle** [comment]
@vassilevsky if you have ideas for how we can make this clear we'd gladly accept a patch/suggestion
