### ISSUE TITLE
schema: add constructor for types.Isolator

### ISSUE THREAD

**Issue by alban** [appc/spec#268]
``types.Isolator`` does not have an constructor. Since the field ``types.Isolator.IsolatorValue`` is not exported, the only way to instantiate an isolator is by unmarshalling a string.

Additionally, for the same reasons there are no ways to create a non-empty ``NewLinuxCapabilitiesRetainSet`` or ``NewLinuxCapabilitiesRevokeSet`` without unmarshalling a string.

This is needed by https://github.com/appc/spec/pull/258.

**Comment by jonboulle** [comment]
Fixed by #517
