### ISSUE TITLE
spec: need a way to declare a range of ports

### ISSUE THREAD

**Issue by eyakubovich** [appc/spec#272]
Some apps utilize a range of public ports (e.g. FTP server) and appc should support this use case. Any router will have an option to DMZ a range of ports as a demonstration that it's a valid use case.

**Comment by philips** [comment]
Each ftp port has a use case though, can't they each be named separately?

**Comment by eyakubovich** [comment]
The data ports are a range from which a server randomly selects one and gives it to the client to connect to. This is passive mode. It can be the whole ephemeral range or restricted to something like 2k ports.

**Comment by jonboulle** [comment]
@eyakubovich can you come up with a proposal for this?
