### ISSUE TITLE
spec: meta discovery example includes mystery ?torrent parameter

### ISSUE THREAD

**Issue by marineam** [appc/spec#283]
Under https://github.com/appc/spec/blob/master/SPEC.md#meta-discovery we have one example reporting:

```html
<meta name="ac-discovery" content="example.com https://storage.example.com/{os}/{arch}/{name}-{version}.{ext}?torrent">
```

But later says:
```
aci: https://storage.example.com/linux/amd64/reduce-worker-1.0.0.aci
```

Where'd the `?torrent` go? What does `?torrent` even mean? It isn't otherwise mentioned in the spec.

Related, there is a second template `hdfs://storage.example.com/{name}-{version}-{os}-{arch}.{ext}` which is also dropped from the following example. Either it shouldn't appear in the first example or the alternate htfs location should be noted in the list of expanded URLs.

**Comment by jonboulle** [comment]
fixed by #288
