### ISSUE TITLE
spec: alternative termination signals?

### ISSUE THREAD

**Issue by jonboulle** [appc/spec#290]
In the spec we talk in passing about an executor passing SIGTERM to the processes running in a pod, and how that will result in e.g. the `post-stop` eventHandler being run. It was raised in #12 that we should consider different kinds of termination signals such as HTTP GETs and/or Execs. Opening this issue to discuss.

**Comment by jheiss** [comment]
#188 is similar?

**Comment by jonboulle** [comment]
You're right, this can probably just be folded into that. Thanks for pointing that out!
