### ISSUE TITLE
spec has bad gpg encryption command

### ISSUE THREAD

**Issue by hawicz** [appc/spec#292]
In SPEC.md, the gpg command to encrypt the aci uses the same name for the output and input, which can't work because as soon as it opens and truncates the output file it looses the input data.
Instead of:
> gpg --output reduce-worker.aci --digest-algo sha256 --cipher-algo AES256 --symmetric reduce-worker.aci

It should be something like:
> gpg --output reduce-worker.aci.out --digest-algo sha256 --cipher-algo AES256 --passphrase foo --symmetric reduce-worker.aci
> mv reduce-worker.aci.out reduce-worker.aci

**Comment by philips** [comment]
@hawicz Good call, would you like to send a patch to fix this?

**Comment by jonboulle** [comment]
fixed by #328
