### ISSUE TITLE
spec: Trim down PODs

### ISSUE THREAD

**Issue by robertvazan** [appc/spec#296]
PODs are part of an API between ACE and orchestration tools. See issue #293 for details about proposed API. Once there is an orchestration tool, it becomes apparent that some features of PODs are duplicating orchestration functionality. This is bad for the standard, because it bloats implementations and it accelerates aging of the standard by introducing functionality that will be soon obsolete.

I suggest removing redundant parts of the POD spec:

- Only one app. Multiple apps per POD are obvious orchestration functionality.
- App is only identified by image ID. Orchestration tool can easily do its own dependency matching if it wants to.
- Trim down indirections in volume and port mappings. Nobody is going to write PODs by hand. Orchestration tools will generate PODs from their own configuration.

**Comment by robertvazan** [comment]
Correction: Image ID must be accompanied by some information that permits location of registry via DNS. Once registry is reached, further search can continue via image ID.

**Comment by philips** [comment]
I am going to close this as I don't think it adds much to the conversation we are having in #293.
