### ISSUE TITLE
actool: check/update manifest acVersion when building an ACI

### ISSUE THREAD

**Issue by iaguis** [appc/spec#298]
Since the [ImageManifest](https://github.com/appc/spec/blob/master/SPEC.md#image-manifest-schema) includes the spec version, a lot of ACI build scripts will use the current version and forget to update it when the spec gets updated. We could avoid this version rot by being smarter when we build ACIs.

Proposal from [coreos/fleet#1191](https://github.com/coreos/fleet/pull/1191/files#r28578245):

> Maybe `actool build` can check the acVersion in the manifest, change it to the last version and:
>
> * either update other fields if there are incompatibilities between the last version and the specified version
> * or complain (or print a warning?) that the manifest is too old: "acVersion is too told. Please fix your manifest."
> * `actool validate` can print this warning/error

**Comment by jonboulle** [comment]
relates to #313

**Comment by jonboulle** [comment]
@iaguis want to take a stab at this?

**Comment by iaguis** [comment]
Sure. Thinking more about it:

1. We can blindly change the version when building the ACI and hope everything works. Not a fan.
2. We can error out when the manifest has an *old* version (that is, older than actool's). This means we're forcing the user to use the latest version in their manifest, maybe it's too strict. We could just print a warning and build the ACI anyway[1].
3. We can create an add update functionality. This will require additional work every time we update the scheme version and change the manifest format.

The ideal solution would be the last one but is it worth the trouble? Maybe after 1.0.

For now I suggest option 2 with a warning so we encourage aci builders to update their manifests but we don't refuse building the ACI.

[1]: If we do a destructive update to the manifest layout in the future, we'd a way to generate ACIs for old versions of the spec.

**Comment by iaguis** [comment]
I've implemented option 2 in #322

**Comment by jonboulle** [comment]
Fixed by #322
