### ISSUE TITLE
versioning of the spec itself

### ISSUE THREAD

**Issue by vbatts** [appc/spec#313]
While the spirit of the spec feels like maintaining a forward-compatible spec, it seems there is a need for versioning of the spec itself.

Like actool to check correctness, there will be a need for loose coupling of a new change and the compliance of ACIs to this change. There is no field for this (yet), but could be introduced, and infer that manifests without an `AC_VERSION` (or similar) are less than the initial version that includes versioning.

With a version of the spec then implementors can more clearly pin and implement. and staged their release criteria (as opposed to a moving target)

/cc @jonboulle @philips

**Comment by jonboulle** [comment]
@vbatts what is wrong with

> acVersion (string, required) represents the version of the schema specification that the manifest implements (string, must be in semver format)

in both image and pod manifests?

**Comment by vbatts** [comment]
ohman. I read that as an arbitrary version of the aci. Don't know what the annotation of "version" didn't flag in my brain for that.

**Comment by jonboulle** [comment]
@vbatts can we clarify?

**Comment by vbatts** [comment]
absolutely. I can start a section for it, in addition to the loose ref link
PR I just opened

**Comment by vbatts** [comment]
thinking further on this, it needs its own section, because there should be
a stance on version compatibility. e.g. "I'm building pod manifest from
version 0.x.y and it includes an app that is from from 0.x.y-1, is that
okay?", etc.

**Comment by jonboulle** [comment]
Yes, fair point..

**Comment by vbatts** [comment]
I updated my PR, but will have to address compatibility in a bit
