### ISSUE TITLE
spec: pod and mount namespace

### ISSUE THREAD

**Issue by ibukanov** [appc/spec#318]
The spec states that the shared context for a pod includes the mount namespace. I am not sure what exactly it means given that each application runs in its own chroot and mount points can only shared using explicit bind statements. Shouldn't the spec drop the mount namespace from the shared context?

Also, it is not clear what is the exact behavior of a pod volume with `kind=empty` that is mounted for several applications. The specs states that *writes go to the app's chroot* which I read as implying that each app gets its own volume and these are not shared. Or is the intention that such volume is shared but its exact location on the host is implementation-dependent?

**Comment by jonboulle** [comment]
>  I am not sure what exactly it means given that each application runs in its own chroot and mount points can only shared using explicit bind statements. Shouldn't the spec drop the mount namespace from the shared context?

I have actually debated this myself, it might be easier to move to the way Kubernetes describes it which is just that they must be able to share certain volumes. I think there is an issue somewhere for that...

**Comment by jonboulle** [comment]
> Also, it is not clear what is the exact behavior of a pod volume with kind=empty that is mounted for several applications. The specs states that writes go to the app's chroot which I read as implying that each app gets its own volume and these are not shared. Or is the intention that such volume is shared but its exact location on the host is implementation-dependent?

This is https://github.com/appc/spec/issues/183. Feel free to add some thoughts or put up a proposal there (I'm finding that PRs attract more robust discussion+progress than open issues ;-)

**Comment by jonboulle** [comment]
reference: https://github.com/GoogleCloudPlatform/kubernetes/pull/4701#discussion_r25125656

**Comment by philips** [comment]
I am fine updating the language to say they can share volumes and remove the mount namespace thing.

**Comment by jonboulle** [comment]
addressed in #371
