### ISSUE TITLE
spec: standard time string format

### ISSUE THREAD

**Issue by vbatts** [appc/spec#330]
In the `annotations`, the value for key `created` is RFC3339.

Should we make a section for standard formats like this?

**Comment by jonboulle** [comment]
@vbatts We could I guess; I think we should tackle that after splitting apart the spec - #291 
Right now it's codified in the schema types.

**Comment by jonboulle** [comment]
@vbatts since we now have a bunch of these [types defined in the spec](https://github.com/appc/spec/blob/master/SPEC.md#types) feel free to tackle this before #291 happens
