### ISSUE TITLE
Clarify dependency matching wild-card vs don't-care

### ISSUE THREAD

**Issue by thockin** [appc/spec#356]
"It is absent from the dependency specification and present in the dependency's ImageManifest" ... "wildcard".

This is not wildcard as I understandit, this is "don't care".  Wildcard implies that you expect it to exist but it must be in some range of values.

**Comment by jonboulle** [comment]
> Wildcard implies that you expect it to exist but it must be in some range of values.

IMHO that is exactly what it is: the label exists but can be of any value. (Although the fact that I added scarequotes means I probably wasn't quite convinced myself...)

Is there a better technical term for "don't care"? ;-)

**Comment by thockin** [comment]
On re-reading, I guess my main point is that this criteria is "obviously" a don't care, but then you did say "match" as opposed to it being a selector.  It's fine.
