### ISSUE TITLE
ACE: network clarifications

### ISSUE THREAD

**Issue by thockin** [appc/spec#357]
"should be configured with an IPv4/IPv6 address" -- How many interfaces are required?  v4 AND v6, v4 OR v6, or v4 XOR v6?

Is loopback part of the spec?  Who sets up the loopback device? What guarantees does it have for v4 vs v6?

**Comment by jonboulle** [comment]
Hrm, we sort of implicitly touch on this in the resource/network-bandwidth isolator:

>   **NOTE**: Network limits MUST NOT apply to localhost communication between apps in a pod.

I don't see a good reason to not be more explicit in the networking section about providing a loopback interface - can you take a pass at wording this?

Re: IPv4/IPv6, OR/AND seems reasonable to me.

/cc @eyakubovich

**Comment by thockin** [comment]
I would if I knew the intentions, though it might be a bit - I have a lot to get to in the coming weeks.

**Comment by jonboulle** [comment]
fixed by #368
