### ISSUE TITLE
Volumes: three-level volumes definitions are confusing

### ISSUE THREAD

**Issue by thockin** [appc/spec#364]
The whole three-level volume thing is confusing to me (and I dreamed up the kubernetes two-level system, so ...).  I think this warrants some energy in simplifying, but I am guessing this ties into concerns about "what" to run and "how" to run it.

Specifically, the need to expresss mountpoints on an image: Does this mean that I can not do clever things with mount points and extant images?  E.g. bind mounting host stuff in to random places... This has been very powerful in Dockerland - e.g. injecting a binary via a volume, using that as the entrypoint, and slingshotting to the "real" entrypoint, all without the container image's participation.

I get the desire to say "I only accept volumes on path X" but I think that is not sufficient to prevent trouble, and I think it is over-constraining.  At the very least, it deserves some thorough explanation.  But having to thread volume info into three places is just too much for my poor brain.

**Comment by jonboulle** [comment]
This issue (arbitrary mounts) emerged recently in our implementation:
https://github.com/coreos/rkt/issues/761
https://github.com/coreos/rkt/pull/853

**Comment by jonboulle** [comment]
> Does this mean that I can not do clever things with mount points and extant images? E.g. bind mounting host stuff in to random places... This has been very powerful in Dockerland - e.g. injecting a binary via a volume, using that as the entrypoint, and slingshotting to the "real" entrypoint, all without the container image's participation.

Well, since everything is overridable by the executor via PodManifest, you can indeed do this and be compliant with the spec - the proposed `--inject-volumes` flag for rkt does exactly this: https://github.com/coreos/rkt/pull/853/files#diff-0321d59a96842ba88f277bbab5b32852R131

So the current spec definitely allows such arbitrary behaviour even if it's not immediately obvious. Would just calling this out more clearly seem sufficient? Or would you still prefer more drastic simplification?

**Comment by thockin** [comment]
This is where my issue list gets fun.  I certainly don't intent to impose my worldview on everyone, but I *do* find the three levels to be awkward.  Is the goal to give ACI creators the ability to say "I expect a volume on /foo and if I don't have one, it is an error" ? That's how it reads.  If so, I'm not sure I buy the utility.  Volumes are not created equal, but I don't think you want ACI creators dictating "here I want a tmpfs".  I think that really becomes part of the HOW, not the WHAT.

Or is there some other problem that the extra indirection solves, in exchange for its cost?

**Comment by ibukanov** [comment]
I second the idea of allowing the pod spec to mount volumes in containers directly bypassing the notion of explicit mount points. Those are important in the docker land where the notion of the pod does not exist and volumes is the only way to share data among containers if one wants to avoid dependency on implementation details. The pod and its notion of empty volumes significantly reduces the need for extra abstraction level of mount points.

**Comment by ibukanov** [comment]
After considering this farther, it seems that the notion of a name for both mount points and volumes is unnecessary indirection. It requires to invent a lot of extra names when the mount path in the container is sufficient to identify the storage.

So the idea is to drop the name field from the elements of the `mountPoints` array and remove the `mounts` array from the app object. Then make the `volumes` array optional in the pod manifest. By default all mount points gets own private storage. To share storage between apps in the pod or even between different mount points in the same application the volume session should lists all mount points that share the storage in the volume list using app names and mount point paths.

Here is how the example form https://github.com/appc/spec/blob/master/SPEC.md#pod-manifest-schema looks like with this proposal (all `mounts` arrays are removed):

```
"name": "reduce-worker",
...
"mountPoints": [ { "path": "/mnt/foo" } ],
...
 "name": "backup",
...
"mountPoints": [ { "path": "/mnt/bar", "readOnly": true } ],
...
 "volumes": [
        {
            mounts: [ ["reduce-worker", "/mnt/foo"], ["backup", "/mnt/bar"] ]
        }
    ],
```
where `mounts` is a list where each element is also a list where the first element is the name of the app and the rest of elements lists all the paths from the app that share the volume. When reified, the `volumes` array becomes: 
```
 "volumes": [
        {
            mounts: [ ["reduce-worker", "/mnt/foo"], ["backup", "/mnt/bar"] ],
            "kind": "host",
            "source": "/opt/tenant1/work"
        }
    ],
```

For a mount point that does not belong to any volume in the manifest the executor adds a reified volume like:
```
 "volumes": [
        {
            mounts: [ ["app-name", "/some/path"]],
            "kind": "host",
            "source": "/opt/whatever"
        }
    ],
```

**Comment by philips** [comment]
We introduced the mount point and name so an image can say where they
expect to have mount points. The problem we were seeing is that people were
having to read docs on Docker images to figure out which paths a given
container expected to be able to write to and perhaps even have that data
persist.

I am OK with getting rid of the indirection and letting the tool that is
running the image take the volumes provided and just map them directly to
paths in the pod manifest so that we have the flexibility of arbitrary
mount points. But, I think having an image describe its mount points is a
nice feature.

Does that work for you @thockin s?

**Comment by thockin** [comment]
I totally understand the desire to say "I expect a volume here" - I have
wanted this.  I'm afraid it's more complex than just "I expect a volume"
though.  Does that include the kind of volume?  empty vs pre-filled?
 read-write vs read-only?  performance charateristics?  durability
characteristics?  It's a very different thing to say "I expect a read-only
directory filled with my security keys stored on tmpfs" than "I expect an
empty directory capable of 1000 IOPS which is durable across machine
crashes".

I'd rather sort that out and add it in than get it wrong.  My feeling is
that the strongest thing we can offer is a hint.

**Comment by kelseyhightower** [comment]
@thockin @jonboulle I ran into this yesterday while converting a bunch of docker Kubernetes images to ACIs. I was a bit confused on how to articulate mounts, volumes, and mountPoints in my manifest. Turns out I only really needed to specify mountPoints on the app, which allowed me to use the `--volume` flag during rkt run to get everything working.

Is the fix here to clean up the docs, or cleanup the spec and make what I'm doing below the default and only way of doing things?

```
$ actool cat-manifest --pretty-print kubelet-0.19.0.aci
```
```
{
    "acKind": "ImageManifest",
    "acVersion": "0.5.1",
    "name": "kubelet",
    "labels": [
        {
            "name": "version",
            "value": "0.19.0"
        },
        {
            "name": "os",
            "value": "linux"
        }
    ],
    "app": {
        "exec": [
            "/kubelet"
        ],
        "user": "0",
        "group": "0",
        "environment": [
            {
                "name": "PATH",
                "value": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            }
        ],
        "mountPoints": [
            {
                "name": "var-lib-docker",
                "path": "/var/lib/docker"
            },
            {
                "name": "var-lib-kubelet",
                "path": "/var/lib/kubelet"
            },
            {
                "name": "root",
                "path": "/rootfs",
                "readOnly": true
            },
            {
                "name": "var-run",
                "path": "/var/run"
            },
            {
                "name": "kubernetes-manifests",
                "path": "/etc/kubernetes/manifests"
            },
            {
                "name": "sys",
                "path": "/sys",
                "readOnly": true
            },
            {
                "name": "resolv-conf",
                "path": "/etc/resolv.conf",
                "readOnly": true
            }
        ],
        "isolators": [
            {
                "name": "os/linux/capabilities-retain-set",
                "value": {
                    "set": [
                        "CAP_NET_ADMIN"
                    ]
                }
            }
        ]
    },
    "annotations": [
        {
            "name": "created",
            "value": "2015-06-15T02:13:40Z"
        }
    ]
}
``` 

### Run it

```
/usr/bin/rkt --insecure-skip-verify run \
 http://storage.googleapis.com/rktscience/kubelet-0.19.0.aci \
 --volume root,kind=host,source=/ \
 --volume kubernetes-manifests,kind=host,source=/etc/kubernetes/manifests \
 --volume sys,kind=host,source=/sys \
 --volume var-lib-docker,kind=host,source=/var/lib/docker \
 --volume var-lib-kubelet,kind=host,source=/var/lib/kubelet \
 --volume var-run,kind=host,source=/var/run \
 --volume resolv-conf,kind=host,source=/etc/resolv.conf \
 -- \
 --address=0.0.0.0 \
 --api-servers=http://localhost:8080 \
 --containerized \
 --enable-server \
 --hostname-override=127.0.0.1 \
 --config=/etc/kubernetes/manifests \
 --machine-id-file=/rootfs/etc/machine-id \
 --v=2
```

**Comment by jonboulle** [comment]
Simplified in #495
