### ISSUE TITLE
Metadata endpoints are too vague

### ISSUE THREAD

**Issue by schancel** [appc/spec#373]
Should include content type and JSON schema references for the returned values.

E.g. is `/acMetadata/v1/pod/uuid` supposed to be a JSON object, raw bytes, base64 encoded, or a canonical UUID of the pod?

**Comment by jonboulle** [comment]
@schancel @eyakubovich can one of you tackle this please?

**Comment by jonboulle** [comment]
Ping @schancel

**Comment by schancel** [comment]
Pong.

**Comment by philips** [comment]
@schancel I think @jonboulle is asking if you could help out with a PR.

**Comment by jonboulle** [comment]
yes, that's what I was asking :-)

**Comment by schancel** [comment]
Yes, I was acknowledging that.  :)

**Comment by schancel** [comment]
I think we closed this one up with my PR?
