### ISSUE TITLE
AC name type formula bad

### ISSUE THREAD

**Issue by globalcitizen** [appc/spec#384]
Under the DNS notion, see http://stackoverflow.com/questions/106179/regular-expression-to-match-dns-hostname-or-ip-address for a reference on matching. Current spec is not a valid match, even if you exclude international extensions.

**Comment by thockin** [comment]
I don't see it - do you have an example of an invalid name DNS name that
this regex matches?

**Comment by globalcitizen** [comment]
Where any part of the domain is over 64 characters?

**Comment by thockin** [comment]
Yeah, OK.  My opinion is that length validation makes an already complex
regex way more complicated.  Kubernetes does length validation out of band
from regex checking.  But as you point it out, we also don't handle
individual over-long tokens, just total length.  Thanks, will file a bug

**Comment by jonboulle** [comment]
We don't actually say anywhere in the spec that an AC Name Type *must* be a valid DNS name, it's just recommended that they are for discovery (which is not mandatory). Let's address the length in #341.
