### ISSUE TITLE
acKind: not very legible

### ISSUE THREAD

**Issue by globalcitizen** [appc/spec#385]
Not very readable to a lay observer.

Secondly, if there are intended to only be two types (pod and image), a boolean may be a better option.

Also, might be worth removing in the normal case, and defaulting to `ImageManifest`? This keeps things cleaner.

**Comment by jonboulle** [comment]
Can you help me understand what is not readable?

/cc @vbatts

Also we avoided a boolean for future compatibility, and would prefer
explicitness over implicit. Generally speaking these are targeted at
machines not humans.
Am 06.05.2015 09:30 schrieb "Walter Stanish" <notifications@github.com>:

**Comment by globalcitizen** [comment]
My point was `acKind` is meaningless unless I have read your documentation, whereas if it were `'isMultiContainerPodDefinition':true` then it would be clearer.

I expected the response of extensibility when asking this question, but I would ask another question in return: if you are planning to add new types then I would query what those are? (Each type will likely have differing data structure requirements, which will make things progressively uglier... might be simpler just to add 'metadata_version':'1.0.0' at the top?)

**Comment by vbatts** [comment]
Again, by having a "kind", that folks can implement too, allows interoperability with the spec, but could even let someone vet out a new kind, that has undetermined expectations. But by making a field like that boolean, you have only two behaviors. That is a future pain and complication.

PodManifest has a lot of overlap with ImageManifest, granted. But they may likely be a need for a ServiceManifest to describe a collection of pods and/or images that span hosts. Immediately the flexibility is needed while this new type is vetted.

If this can be more legible, feel free to propose how. For now, let's not lock in only two types for a pre-1.0 spec. :-) I'm going to close this as I think the point as been addressed. We can continue conversation on specific points to clarify.
