### ISSUE TITLE
resource isolators: Dual-tier system conceptually broken

### ISSUE THREAD

**Issue by globalcitizen** [appc/spec#390]
The approach apparently taken to normalization of `cgroup` subsystem limits is to create a two-tier resource control concept, wherein an optional `request` tier defines a minimum resource quantity (which defaults to `limit`, if specified), and a `limit` tier which defines a maximum resource consumption.

How well does this attempt at normalizing the `cgroup`-style cross-subsystem resource control numbers work practically?

In fact it seems there are two separate concerns here really, a start-time concern ("I need at least X amount of resource Z or I will refuse to run") and a run-time concern ("If I ever ask for more than Y of resource Z, kill me"). A closely related concern is actual resource use. Finally, with the nominally flexible events system triggered events might exceed purely 'kill' and feed back to the in-container code itself.

Some resources (eg. storage) must often be pre-allocated and cannot grow (though they can grow with say `zfs` or `tmpfs` or something); which makes the second figure useless.

In other cases, a resource might temporarily lose availability below requested quantities though initial availability is good.

It sounds like the fundamental abstraction used here needs a rethink.

**Comment by jonboulle** [comment]
I am not really sure what you're referring to with "normalization of cgroup subsystem limits"; we shouldn't even be mentioning cgroups in the spec (I see the word is used in a couple of places, which should be cleaned up, but it's specifically and intentionally not discussed in the resource isolators section)

As for the rest of what you describe, it sounds very much the same concern as #361 so let's work through it there.

**Comment by jonboulle** [comment]
Also relevant: #359

**Comment by xiang90** [comment]
@globalcitizen 

From my understanding, `request` is a runtime guarantee (yea it is also a start time checking as you mentioned).  `limit` is a runtime limitation.  

So I cannot agree they are totally separate concerns as you described.

**Comment by globalcitizen** [comment]
@xiang90 : The re-raising of these points as #361 is perhaps clearer, would you be so kind as to offer your opinion there?
