### ISSUE TITLE
Dependencies should be renamed/made explicit

### ISSUE THREAD

**Issue by globalcitizen** [appc/spec#394]
`dependencies`: Strangely, a request for `unionfs`/`aufs`-style root filesystem layering. Obviously some kind of direct import from docker-land. This could be a reasonable feature if it were better defined, but in fact on different platforms and filesystem versions is likely to handle collisions and other such edge cases in very different ways. Unclearly named (`filesystemParentLayers` might be closer to reality), at the very least. In addition, the feature makes determinism optional (no need to specify precisely which layer you are looking for), which is bug-causing and therefore bad.

**Comment by jonboulle** [comment]
I think this is now sufficiently explicit, mentioned:
- in the [Image Manifest](https://github.com/appc/spec/blame/master/SPEC.md#L115) section
- in the [Filesystem Setup](https://github.com/appc/spec/blob/master/SPEC.md#filesystem-setup) section
- in the [Image Manifest schema](https://github.com/appc/spec/blame/master/SPEC.md#L767)

Let's use #295 to track the question of determinism optionality.

**Comment by globalcitizen** [comment]
OK, split determinism to #295....

I still don't feel the purpose explicit because the name and the purpose remain relatively divergent within the context of an untrained set of eyes looking at a JSON `metadata` definition.

The documentation should not need to be read to understand the JSON.

*Documentation is an admission of failure.* - Eric S. Raymond, The Art of Unix Usability (2004)

This perspective is partly supported by the observation of another popular quote on the subject:

*Arnold's Law of Documentation: If it should exist, it doesn't.  If it does exist, it's out of date.  Only documentation for useless programs transcends the first two laws.*

... ie. you wind up with a 'multiple source of truth' scenario where the subject and the documentation, while co-dependent for proper comprehension, wind up out of sync. That's *precisely* what just happened.

I would still, therefore, argue strongly for renaming this field.

**Comment by jonboulle** [comment]
> I still don't feel the purpose explicit because the name and the purpose remain relatively divergent within the context of an untrained set of eyes looking at a JSON metadata definition.

I think there is exhaustive prior art here with countless package management systems on different platforms (not to mention the term "dependency hell"). I don't see a significant divergence in our usage: dependent images (packages) that need to be transitively installed for this image (package) to be run.

> ... ie. you wind up with a 'multiple source of truth' scenario where the subject and the documentation, while co-dependent for proper comprehension, wind up out of sync. That's precisely what just happened.

How? They have never been out of sync. The dependencies concept has not changed since we introduced it.

**Comment by globalcitizen** [comment]
> How? They have never been out of sync.

Apologies, I was not clear enough. What I meant was that `dependencies` suggests package-style dependencies. However, what you are actually specifying here is filesystem layers. In that sense, informed by the same "countless package management systems" experience you refer to, the use of the term dependencies is unclear/misleading in this context.

As the clear subject here is filesystem layers, an alternative term such as `parentFilesystemLayers`, `filesystemLayers` or `filesystemSourceLayers` or `filesystemParentLayers`, `sourceFilesystemLayers` or `inheritedFilesystemLayers` would be clearer.

Frankly though, I'm not convinced that the FS layering notion belongs in-spec as it could be resolved by an ACE outside of spec in the spirit of minimalism. (See also #295 comment after the two issue references)
