### ISSUE TITLE
spec: ACName restrictions prevent discovery of valid urls

### ISSUE THREAD

**Issue by soellman** [appc/spec#406]
I haven't looked very deeply into how discovery works, but my quay.io org name has an underscore in it, and rkt can't pull private ACIs from there because ACName complains (and rkt just gives an erroneous error: rkt/images.go:261).

I can provide a PR, but is this an unintended consequence, or is there a reason ACName is more restrictive than common URL characters?

I'm new here so pardon any ignorance :)

**Comment by jzelinskie** [comment]
linking to https://github.com/coreos/rkt/issues/898

**Comment by philips** [comment]
I am OK with taking this change. Anyone else from the @spec team?

**Comment by dgonyeo** [comment]
If you're going to modify the regex that identifies the presence of invalid characters, it might be worth adding all the [valid characters](http://tools.ietf.org/html/rfc3986#section-2) allowed in URLs.

**Comment by soellman** [comment]
Should I just add the URL unreserved chars to the regex, or the full monty with delimiter chars?

**Comment by jonboulle** [comment]
@thockin thoughts on this?

**Comment by yifan-gu** [comment]
Any consensus on this? Being strict v.s. opening the door for all validate URL characters?
My vote is being strict for now, so adding just those URL unreserved chars("-" / "." / "_" / "~") because I can't see much usage for chars like `!` `$` `&` (any examples??)

Actually I don't even know when `~` will be used?

**Comment by mpasternacki** [comment]
`~` can be used if somebody hosts images in old-school `~/public_html/` directory or similar `/~user/` convention. The `?&` characters should not be allowed, as they are used in query strings and this can open whole new can of worms (where to add the `.gpg` suffix: before `?` or at the end of whole string?).

I wonder about URL-encoding, though. Maybe it would enable using all kinds of URLs without compromising the simplicity if we allowed URL-encoding of remaining characters?

Another thing: do we need to say something about normalization and path traversal? If ACName maps to URLs, then `foo/bar`, `foo/./bar`, `foo/baz/../bar` etc may be equivalent. Or do we just use the literal name, and let the server hosting the ACI deal with paths?

**Comment by jzelinskie** [comment]
I don't know if we want to get in the situation where we're encoding and decoding names, but I still think something like [punycode](https://en.wikipedia.org/wiki/Punycode) should be at least mentioned in this conversation since this is how the problem was solved for DNS.

**Comment by thockin** [comment]
For kubernetes we opted to expand when we have real use cases.  We do not support ~, for example, but this is somewhat different - this is sort of assumed to be resolvable as a URL, right?

**Comment by soellman** [comment]
So it sounds like maybe we just want the unreserved chars for now?

**Comment by yifan-gu** [comment]
> So it sounds like maybe we just want the unreserved chars for now?

+1 for this. I was going to modify https://github.com/appc/spec/pull/398 for this. But my computer crashed today...

**Comment by yifan-gu** [comment]
Also, shall we consider adding upper case letters ?

**Comment by yifan-gu** [comment]
FWIW, in docker, the repository can contain `. - _ / :` and uppercase letters.

**Comment by jonboulle** [comment]
@yifan-gu this can be closed right?

**Comment by yifan-gu** [comment]
@jonboulle Yes I think so! Users should now be happy with most their URLs.

Though for the rkt issues, we will need to cut a release for spec and bump the dependency :)
