### ISSUE TITLE
schema: add armv6l as valid arch for linux (Raspberry Pi 1)

### ISSUE THREAD

**Issue by alban** [appc/spec#417]
Some arm architectures are already added by #304 for #284. But according to https://github.com/coreos/rkt/issues/730#issuecomment-105490008 this is not enough for Raspberry Pi 1:

> @alban, if someone would like to use rkt on a Raspberry Pi 1 (there are about 5 million devices out there), the minimum supported ARM version should be ARMv6. This is also the default when building a GOLANG binary with GOARCH=arm. For this reason I strongly recommend to support armv6l too! BTW, a armv6l binary is compatible and runs absolute fine on a `armv7l´ machine - but not the other way around.

/cc @DieterReuter

The current support is:
```
var ValidOSArch = map[string][]string{
        "linux":   {"amd64", "i386", "aarch64", "armv7l", "armv7b"},
        "freebsd": {"amd64", "i386", "arm"},
        "darwin":  {"x86_64", "i386"},
}
```

**Comment by alban** [comment]
@DieterReuter : would you like to do write PR for this? Do you have the hardware to test?

https://github.com/appc/spec/blob/master/schema/types/labels.go#L9

**Comment by DieterReuter** [comment]
@alban, I do have the hardware available and will prepare a PR. Give me just a few days, please!

**Comment by jonboulle** [comment]
@DieterReuter how goes?
