### ISSUE TITLE
baci is totally out of date, any replacer?

### ISSUE THREAD

**Issue by linfan** [appc/spec#420]
The tool `baci` mentioned in this specification is [actually NOT compatible with the latest appc and rkt any more](https://github.com/sgotti/baci/issues/3).

Do CoreOS plan to have another official tool to replace it?

Also the Dockerfile format is NOT 100% fit for Appc images, e.g. it does not support exposing a MountPoint. It do have a far way to go..

**Comment by jonboulle** [comment]
sgotti is best placed to comment on the specifics of baci. There are some proposals being worked on for alternative build workflows/tools, but nothing quite ready to note here; as soon as they turn into tangible projects we'll be sure to update the README to reference them. Thanks.
