### ISSUE TITLE
spec: clarification needed for dependencies unpacking

### ISSUE THREAD

**Issue by mpasternacki** [appc/spec#425]
> An app's filesystem must be *rendered* in an empty directory by the following process (or equivalent):
> - The `rootfs` contained in the ACI is extracted
> - If the ACI contains a non-empty `dependencies` field in its `ImageManifest`, the `rootfs` of each dependent image is extracted, in the order in which they are listed
> - If the ACI contains a non-empty `pathWhitelist` field in its `ImageManifest`, *all* paths not in the whitelist must be removed

What should happen if one of dependencies include a path that is already present in the image? Straightforward implementation of the above process would overwrite the image's file with one from the dependency. On the other hand, common sense would suggest that this reading is not intentional; this definitely is not the behaviour I would expect.

I would expect that a dependency is similar to a "parent image" in Docker: a Ruby application ACI extends (and depends on) a Ruby runtime ACI, which in turn extends (and depends on) bare distribution ACI. Files from Ruby runtime ACI would overwrite files from the bare distribution, and files from the Ruby application ACI would overwrite files from both Ruby runtime and bare distribution.

Please clarify: is my understanding of the use case wrong here? In either case, more explicit phrasing in this part of the spec would be useful.

If I am wrong, and dependencies shouldn't be used to provide parent/child inheritance like in Docker, is there any good approach to distribute only the new in the ACI if the "parent" image is discoverable?

**Comment by jonboulle** [comment]
@mpasternacki Your understanding of the use case is correct and the wording is wrong here, I'm afraid  - the rootfs of the ACI should be extracted _after_ any dependencies. In the schema definition we describe it properly:
> dependent application images that need to be placed down into the rootfs before the files from this image (if any).

but clearly this is at odds with the passage you've highlighted.

Are you up for submitting a PR to fix this? otherwise I can take it.

I suggest we also eliminate some of the redundancy in these explanations (perhaps consolidating the definition one place and referencing it from the other two):
https://github.com/appc/spec/blame/f5dcd33c4808894f111618204ae57f8d35408424/spec/aci.md#L70
https://github.com/appc/spec/blame/f5dcd33c4808894f111618204ae57f8d35408424/spec/aci.md#L236
https://github.com/appc/spec/blame/f5dcd33c4808894f111618204ae57f8d35408424/spec/ace.md#L29

**Comment by mpasternacki** [comment]
Thanks for the clarification! Will submit PR with a fix (tomorrow, it's almost midnight here), I just wanted to know how to fix it first.

**Comment by mpasternacki** [comment]
While we're at the rendering: how should directories in `pathWhitelist` be treated: kept with their contents, or just the directory? Does a trailing slash or lack of it make a difference?

**Comment by krobertson** [comment]
The way I had implemented PathWhitelist for Kurma just yesterday was:

1) Trailing slash means the directory and all of its contents
2) Non-trialing slash meant just a file, or the directory without its contents. So, `/var/lib/mysql` would allow the directory to be created, but not any of its contents.

**Comment by krobertson** [comment]
I agree with the clarification too. I'd been talking in IRC with @jonboulle about it yesterday. I didn't spot the incorrect definition, but was confused on it.

**Comment by jonboulle** [comment]
> While we're at the rendering: how should directories in pathWhitelist be treated: kept with their contents, or just the directory? Does a trailing slash or lack of it make a difference?

Sigh, we went through this in https://github.com/appc/spec/pull/354 but I suppose it's still not clear...
Perhaps we could revert to https://github.com/appc/spec/pull/309/files

**Comment by mpasternacki** [comment]
#354 seems to have changed the spec to be less specific. IMO we should either say that directory is never recursive (i.e. `pathWhitelist` is just a list of paths not subject to any interpretation), or go the full way in the other direction and make it  an array of globs (hopefully supporting `**` that matches any char including slash) or regular expressions. In my perfect world, we'd have an array of extended globs, and maybe even a blacklist (to specify patterns to *remove* rather than keep). Having support for everything in `man gitignore` would be even better.

**Comment by jonboulle** [comment]
yes, mea culpa, I removed that extra explanation in response to this comment specifically - https://github.com/appc/spec/pull/354#discussion_r29904243

**Comment by jonboulle** [comment]
Re: blacklists: #323

**Comment by mpasternacki** [comment]
Oooh, there even seems to be a Go implementation of `.gitignore` rules: https://godoc.org/github.com/sabhiram/go-git-ignore

**Comment by jonboulle** [comment]
@mpasternacki any chance of getting to this in the next couple of days?

**Comment by krobertson** [comment]
Matching .gitignore standards would be good. Always like something known.

**Comment by jonboulle** [comment]
Bumping to 0.7.0
