### ISSUE TITLE
Do we plan to support CRIU in the spec

### ISSUE THREAD

**Issue by HuKeping** [appc/spec#441]
Hi there,

I did't find any issue or pr that discuss about the CRIU, do we have a plan to support that?

Thanks.

**Comment by krobertson** [comment]
How would it be applicable to the specification in your opinion?

Overall, CRIU is more likely specification to an implementation's choice to support it, rather than something that fits in with the AppC specification.

**Comment by jonboulle** [comment]
I don't think this is ever something we could begin to describe in the spec since it's incredibly implementation specific. But it might be supported in implementations themselves: for example, https://github.com/coreos/rkt/issues/543

**Comment by philips** [comment]
We have the concept of "eventHandlers" in the ACI to have hooks for use cases like reconfiguring the network after a restore. Are there other things you feel are needed?

**Comment by HuKeping** [comment]
Thanks @krobertson @jonboulle , I think I just don't quite understand the AppC and you are right it is more likely to be supported by an implementation itself. I'll take a deeper learning about it :)

Thanks @philips , Not much in my mind, just find it might be useful  in  some production scenarios.
