### ISSUE TITLE
schema/types: volume doesn't allow source paths with special URL characters

### ISSUE THREAD

**Issue by iaguis** [appc/spec#465]
We parse volume parameters with [`url.ParseQuery`](https://github.com/appc/spec/blob/0d1edc37553152577a56f256279992200f142b48/schema/types/volume.go#L101). This means that if the `source` field includes special URL characters they would be interpreted (e.g. `+` is converted to a space) making impossible to use those directories.

**Comment by jonboulle** [comment]
Good catch, do you want to take a look at this? I suppose we need our own simpler impl of ParseQuery?
