### ISSUE TITLE
godeps: update kubernetes dependency

### ISSUE THREAD

**Issue by mikedanese** [appc/spec#470]
As part of rewriting the Kuberentes import path from `github.com/GoogleCloudPlatform/kubernetes` to `k8s.io/kubernetes` we had to update a vendored appc/spec file (rather than Kubernetes vendoring an older version of itself in Godeps/_workspace). This was in https://github.com/GoogleCloudPlatform/kubernetes/commit/62a4d5623c42bd287bbd9ec16be9fb7ee08b8eb8 which was a part of GoogleCloudPlatform/kubernetes#12310. 

The same update should probably be made here or, even better, eliminate this circular dependency. Until then, godep save/restore won't work in the Kubernetes repo.

cc @yifan-gu 

Kubernetes tracking issue GoogleCloudPlatform/kubernetes#12211

**Comment by yifan-gu** [comment]
@mikedanese After #471 get merged I will update https://github.com/GoogleCloudPlatform/kubernetes/pull/8951 Then this should be good :)

**Comment by jonboulle** [comment]
Fixed by #471

**Comment by mikedanese** [comment]
Thanks!
