### ISSUE TITLE
A doubt about the define of struct ImageManifest 

### ISSUE THREAD

**Issue by ChengTiesheng** [appc/spec#482]
Hi dear all, I am doing something about Appc specs, but  I am confused by the ImageManifest struct.
App           *types.App
I want to know why member App defined as pointer, different from other members, I don't get the answer through scanning the code.

Is it a intentional design or is it just a bug? 
 
-------------------------------
```
type ImageManifest struct {
	ACKind        types.ACKind       `json:"acKind"`
	ACVersion     types.SemVer       `json:"acVersion"`
	Name          types.ACIdentifier `json:"name"`
	Labels        types.Labels       `json:"labels,omitempty"`	
	App           *types.App         `json:"app,omitempty"`
	Annotations   types.Annotations  `json:"annotations,omitempty"`
	Dependencies  types.Dependencies `json:"dependencies,omitempty"`
	PathWhitelist []string           `json:"pathWhitelist,omitempty"`
}
```

**Comment by jonboulle** [comment]
@ChengTiesheng it's valid for an ImageManifest to contain no App section, and to achieve that with golang's marshalling it needs to be a pointer. Example: http://play.golang.org/p/28FICldIpy

Does that make sense?

**Comment by jonboulle** [comment]
See also: https://github.com/appc/spec/pull/66
I'm going to close this out since hopefully this addresses your question but feel free to re-open if not.

**Comment by ChengTiesheng** [comment]
@jonboulle, thanks a lot for your detailed reply.
