### ISSUE TITLE
build aci: setting file ownership in the archive

### ISSUE THREAD

**Issue by alban** [appc/spec#498]
When building an aci with [BuildWalker](https://github.com/appc/spec/blob/master/aci/build.go#L89), it adds files in the archive with the same ownership as they are on the filesystem.

It would be useful to be able to change the ownership of files in the aci, without needing to create the aci as root. It is needed for building the stage1 of rkt, see discussion on https://github.com/coreos/rkt/issues/1453#issuecomment-142314125.

At the moment, there is no parameters or callbacks to be able to set `hdr.Uid, hdr.Gid = 0, 0`.

/cc @jellonek

**Comment by jellonek** [comment]
Callback deciding what to do with given patch would be most flexible.
Similar thing would be "nice to have" similar callback to decide how to set/filter object mode (to filter out or to add suid/sgid flags to part of files/directories).
