### ISSUE TITLE
Some clarifications on Fileset.files

### ISSUE THREAD

**Issue by philips** [appc/spec#5]
_From @sgotti on December 8, 2014 16:33_

Hi,

I'd like to help on #140 and #142 as they are the base for other features that I'd like to share (and also for #223)  but first I have some doubts about the "files" entry in the fileset manifest.

The "files" entry is a list of all the files provided by this fileset.

Looking it from another point of view, taking an incremental approach (like, if I understand it correctly, docker does and also like gnu tar incremental archives) won't fit correctly as a fileset can have multiple dependencies applied on different paths (dependencies.root entry). So the solution is to record in the fileset the files provided.

A typical example should be a fileset containing a base distro image. Than on top of it you create another fileset with some new packages installed and other packages removed. This fileset will have all the changed and new files and a fileset manifest where "files" is the list of all the provided files.

So just considering this simpe example (a fileset having 1 dependency with "rootfs": "/")

* If "files" isn't empty than all the files (and maybe strange, also the one provided by this fileset) not listed should be removed from the final layout.

* if "files" is empty (as the specs defines it as optional) that nothing is removed.

Some questions:

1. What to do if all the files inside a directory from a parent fileset are removed leaving an empty directory? The implementation should also remove the directory or leave an empty directory?

2. If the empty directory should be removed how to keep empty dirs? (sometime it's needed to leave empty directories)

I was thinking about a possibile solutions:

*) specify inside "files" also the needed directories (if a name is ending with a slash than it's a directory). To be clear, it doesn't mean the all the files starting from the directory should be whitelisted but just that that the directory shouldn't be removed.

Any other ideas or am I missing something?

_Copied from original issue: coreos/rocket#236_

**Comment by jonboulle** [comment]
Closing as this has been addressed by the latest `dependencies`/`pathWhitelist` section of the spec.
