### ISSUE TITLE
spec: allow empty exec in ImageManifest.App

### ISSUE THREAD

**Issue by yifan-gu** [appc/spec#504]
Today while I am doing `rkt --insecure-skip-verify fetch docker://gcr.io/google_containers/liveness`, I got 
```
error converting docker image to ACI: error building layer: error generating ACI: error writing ACI: error writing manifest: json: error calling MarshalJSON for type schema.ImageManifest: json: error calling MarshalJSON for type *types.App: Exec cannot be empty
```

Wonder maybe we should allow empty exec as the container runtime might override the exec.

**Comment by jonboulle** [comment]
I am kinda on the fence about this one, so I want to push back a little: is there any way we can improve the UX here without making exec optional?

**Comment by yifan-gu** [comment]
@jonboulle Only if give some default cmd when transforming the docker image to aci, like /bin/sh

But as I pointed out, if exec can be totally replace by ace, why it MUST be there at all?

**Comment by jonboulle** [comment]
> But as I pointed out, if exec can be totally replace by ace, why it MUST be there at all?

You could make that argument about literally every required parameter since ultimately they can all be overridden by the executor

**Comment by jonboulle** [comment]
@vbatts @philips ?

**Comment by vbatts** [comment]
even when i've run into this, it seemed like a UI/UX issue, not a spec issue.

**Comment by philips** [comment]
I am sort of OK with an empty exec if we consider the use case of "manifest only" ACIs. Where I have say a syslog-tcp and syslog-tls that both rely on the same underlying layer but that layer has no exec and instead requires one of those two containers to be used.

In general though I feel that ACIs should map directly to an app but I don't see any reason not to allow for the flexibility and just failing to execute a container without an exec. It is a bit like having the exec bit on a file that doesn't have a valid #! or magic number. It is allowed but if you try to exec it the runtime (kernel) will just fail.

**Comment by jonboulle** [comment]
@vbatts can you elaborate?

**Comment by vbatts** [comment]
I had not really contemplated the case of a container that did not need an exec. Despite dependencies, I was thinking of the resulting executable runtime. With this in mind, perhaps having a strict requirement on a manifest having an exec specified is too strict.

The UI/UX concern was just when importing from another image that did not itself have a command, it just seemed like a flag should be present to provide the command for the image being converted.

**Comment by yifan-gu** [comment]
The pro for allowing empty exec in this case is we don't need to have two images on the disk which just differ at exec.

**Comment by jonboulle** [comment]
#505
