### ISSUE TITLE
spec: supplementaryGroups or supplementaryGids?

### ISSUE THREAD

**Issue by iaguis** [appc/spec#511]
#339 introduced supplementary GIDs in the spec.

In [the schema](https://github.com/appc/spec/blob/e040d35a7bb35a343f04c0f022a669968699d06a/spec/aci.md#image-manifest-schema) they are called "supplementaryGids" but the [app parser](https://github.com/appc/spec/blob/e040d35a7bb35a343f04c0f022a669968699d06a/schema/types/app.go#L29) expects them to be called "supplementaryGroups".

**Comment by jonboulle** [comment]
Mea culpa. In this case the code reflects my intention: `supplementaryGroups`, not `supplementaryGids`.

@vbatts @philips @krobertson @mpasternacki any objection to standardising on `groups`?

**Comment by philips** [comment]
@jonboulle groups is a string and supplementaryGroups is a int. Sort of inconsistent.

**Comment by philips** [comment]
I am OK breaking the spec and saying Groups is always an int. This string or int issue is too annoying and never right so we should only put ints in the spec IMHO.

**Comment by jonboulle** [comment]
Right, I think we should just keep it as ints, but the question is what to call it. I have changed my mind on my previous comment and I think we should go with Gids.

**Comment by philips** [comment]
@jonboulle GIDs it is. +1

**Comment by vbatts** [comment]
ints are more definite. string names would be arbitrary and still needing to be resolved.

:+1: to GIDs

**Comment by jonboulle** [comment]
Action is in #516 friends
