### ISSUE TITLE
spec: clarify empty volume permissions

### ISSUE THREAD

**Issue by iaguis** [appc/spec#526]
Capturing a comment by @alban (coreos/rkt#1523)

> With host volumes, we don't need to specify the rights of the mount point because it comes from the existing directory on the host. But with empty volumes, maybe the manifest should tell us how the volume should be created (which owner and permissions).

Perhaps something like:

```
....
"volumes": [
    {
        "kind": "empty",
        "name": "whatever",
        "mode": "0775",
        "user": "1000",
        "group": "1005"
    }
],
...
```

With some sane defaults.

**Comment by jonboulle** [comment]
How do you suggest the user/group fields here be interpreted?

**Comment by alban** [comment]
I would suggest that the user/group fields here can only be numerical.

There is another section of the spec that has user/group fields: in the [Image Manifest](https://github.com/appc/spec/blob/master/spec/aci.md#image-manifest-schema):

> **user**, **group** (string, required) indicates either the username/group name or the UID/GID the app is to be run as (freeform string). The user and group values may be all numbers to indicate a UID/GID, however it is possible on some systems (POSIX) to have usernames that are all numerical. The user and group values will first be resolved using the image's own `/etc/passwd` or `/etc/group`. If no valid matches are found, then if the string is all numerical, it shall be converted to an integer and used as the UID/GID. If the user or group field begins with a "/", the owner and group of the file found at that absolute path inside the rootfs is used as the UID/GID of the process. Example values for the fields include `root`, `1000`, or `/usr/bin/ping`.

However, we can't do the same thing here: the volumes are defined in the [Pod Manifest](https://github.com/appc/spec/blob/master/spec/pods.md#pod-manifest-schema) and not in the [Image Manifest](https://github.com/appc/spec/blob/master/spec/aci.md#image-manifest-schema). The pod can contains several apps with conflicting `/etc/passwd` and `/etc/group` so we would need to choose which app to use to resolve the user/group.

One empty volume can be mounted in several apps, so we cannot just choose the app that uses the volume.

I think the default should be:
```
        "mode": "0775",
        "user": "0",
        "group": "0"
```

**Comment by iaguis** [comment]
I agree :+1:

**Comment by jonboulle** [comment]
Seems reasonable, but do you really intend for the user/group fields to be strings in that case - why not ints?

**Comment by iaguis** [comment]
Yeah, since they're gonna be uid/gid, ints make more sense.
