### ISSUE TITLE
Versioned Container

### ISSUE THREAD

**Issue by hwinkel** [appc/spec#53]
Already asked at rocket, but moved over to the appc project.

It would be great to have versioned container as seen in docker where we have a versioned filesystem like described here:

http://0pointer.net/blog/revisiting-how-we-put-together-linux-systems.html

specially the use of sub volumes and the way how to send and receive the changes could be interesting.

I'm a bit in hurry but promised to at least open the issue. Some ideas will follow.

**Comment by philips** [comment]
@hwinkel I am closing this out since I don't follow what you have in mind. Please re-open if you can provide a follow-up.
