### ISSUE TITLE
releases should include actool / add a release guide

### ISSUE THREAD

**Issue by alban** [appc/spec#530]
Some [appc/spec releases](https://github.com/appc/spec/releases) contain a tarball that includes `actool` compiled, some don't. Releases should consistently provide it.

appc/spec should have a release guide to list the necessary steps to do a release.

This was first reported on https://github.com/coreos/rkt/issues/1626.

**Comment by jonboulle** [comment]
We have `scripts/build-release`, it just didn't get used /cc @vbatts 
I've updated the latest release.

**Comment by alban** [comment]
[rkt documentation (app-container.md)](https://github.com/coreos/rkt/blob/master/Documentation/app-container.md#validating-rkt-as-an-appc-implementation) expects to find:
- https://github.com/appc/spec/releases/download/$VERSION/ace-validator-main.aci
- https://github.com/appc/spec/releases/download/$VERSION/ace-validator-sidekick.aci

But `scripts/build-release` does not upload those and the last release does not have them.

@jonboulle can you update the last release?

**Comment by jonboulle** [comment]
done

**Comment by alban** [comment]
Thanks!
