### ISSUE TITLE
pod manifests should allow setting environment variables

### ISSUE THREAD

**Issue by jaybuff** [appc/spec#531]
https://github.com/appc/spec/blob/master/spec/pods.md doesn't mention setting environment variables for apps.  That said, rkt seems to support it.

**Comment by jonboulle** [comment]
> Pod Manifests also provide the ability to override application execution parameters for their constituent ACIs (i.e. the app section of the respective Image Manifests).

and

> app (object, optional) substitute for the app object of the referred image's ImageManifest. See Image Manifest Schema for what the app object contains.


How can we make this clearer?

**Comment by jaybuff** [comment]
It's already clear.  I was being lazy/tired.  I did find in my browser on pods.md and looked for environment and gave up.

**Comment by jonboulle** [comment]
to be clear, I'm not being passive-aggressive, this has been raised before as something nonobvious, so would love to know how to improve it..

**Comment by jaybuff** [comment]
You could copy and paste the entire app section from the image manifest under this section:

> app (object, optional) substitute for the app object of the referred image's ImageManifest. See Image Manifest Schema for what the app object contains.

But then you have the problem of maintaining the two lists.
