### ISSUE TITLE
Make insecure flag in discovery granular

### ISSUE THREAD

**Issue by krnowak** [appc/spec#545]
In the beginning `insecure` only meant "I want to perform discovery over HTTP if HTTPS didn't work". But right now it means "I want to perform discovery over HTTP if HTTPS didn't work and I even want to send my credentials over HTTP". These meaning should be split.

The functions with `insecure` flag are `discovery.DiscoverPublicKeys`, `discovery.DiscoverEndpoints` and `discovery.DiscoverWalk`. I only checked `discovery/discovery.go` and `discovery/http.go`.

I didn't check if there are some other parts of this project that do similar things.

**Comment by alban** [comment]
I would like an `insecure` flag to allow https with invalid certificates. Right now, it is not possible to use https with invalid certificate even if `insecure=true`. That would be useful for some tests such as https://github.com/coreos/rkt/pull/1822.

So we'd need several flags:
- `insecureTls`: don't check certificates
- `insecureHttp`: allow fallback on http
- maybe: `insecureCredentials`: allow sending credentials on http or on https with unchecked certificate.

**Comment by blixtra** [comment]
What's the status of the `insecureCredentials`? Is this deemed worth having?

**Comment by jonboulle** [comment]
Do we have a use case? Would someone want one but not the other?

**Comment by blixtra** [comment]
IMO, we should just go with insecureHTTP. I would assume that if one uses insecureHTTP then one knows secrets may be sent in the clear and is ok with that.

**Comment by jonboulle** [comment]
Seems reasonable to me.

Chris Kühl <notifications@github.com> schrieb am Fr., 8. Jan. 2016 10:40:

**Comment by blixtra** [comment]
Is it fair to close this then?
