### ISSUE TITLE
Encode empty list as `[]` instead of `null`

### ISSUE THREAD

**Issue by wereHamster** [appc/spec#55]
The manifest of the ACI at https://github.com/coreos/etcd/releases/download/v0.5.0-alpha.4/etcd-v0.5.0-alpha.4-linux-amd64.aci encodes empty lists (`mountPoints`, `annotations` etc) as `null`. I propose to change the encoding to use an empty list (`[]`) or even leave out the key alltogether. I prefer the former because size doesn't really matter here (it's only a few dozen bytes anyways).

**Comment by jonboulle** [comment]
Missed this, should be fixed by #66
