### ISSUE TITLE
schema.types: add constructors for Isolator from types.ResourceMemory or types.ResourceCPU

### ISSUE THREAD

**Issue by alban** [appc/spec#552]
https://github.com/appc/spec/pull/517 added functions `AsIsolator()` to `types.LinuxCapabilitiesRetainSet` and `types.LinuxCapabilitiesRevokeSet` but appc/spec still does not have constructors to build a `types.Isolator` from a `types.ResourceMemory` or `types.ResourceCPU`.

I would need one for https://github.com/coreos/rkt/issues/1735.

**Comment by alban** [comment]
I am not sure of the correct approach. I started to experiment on https://github.com/kinvolk/rkt/commit/6e4858502e53bdc5b6103ff83ed90729e295c3a1.

**Comment by jonboulle** [comment]
For symmetry how about adding `AsIsolator` to those other types as well?

**Comment by alban** [comment]
@jonboulle ok for `AsIsolator` :)

#553
