### ISSUE TITLE
need way to specify hostname (pod name?)

### ISSUE THREAD

**Issue by sjpotter** [appc/spec#572]
k8s requires that the pod name be set to the hostname for the uts namespace, we don't seem to have any ability to do that today.

k8s truncates the pod name to 63 characters

https://github.com/kubernetes/kubernetes/issues/4825

We won't be able to pass e2e tests until this is fixed.

**Comment by jonboulle** [comment]
Why is this a spec issue? Strikes me this is just a requirement that rkt needs to fulfil.

**Comment by sjpotter** [comment]
Spec doesnt define what hostname should be inside the running pod.  I
figured it should.  I.e. rkt can do it but some other implementations
wouldnt know to do it too.

**Comment by jonboulle** [comment]
The spec just says all apps in the pod need to share a hostname, and I'm
not convinced it needs to say anything more than that, at least not
prescriptively.

If you want to add some wording to provide suggestions/examples of what
implementations should do, then by all means go ahead; but I don't see
anything in the current wording that directly blocks the rkt/kubernetes
issue?
