### ISSUE TITLE
spec: application's working directory

### ISSUE THREAD

**Issue by mpasternacki** [appc/spec#59]
Is there an actual reason why the application is required to start in the container's root directory, or is it just scope reduction for first version of the spec?

There is no standard utility that I know of, which would do `chdir()` and then `exec()` the provided command; if the command to run needs a specific working directory, it would need to be wrapped in a shell script, or its exec would be something like `["/bin/sh", "-c", "cd /work/dir && exec \"${@}\"", "arvg0", ACTUAL_COMMAND…]`, which does work, but is kind of ugly, as the app executor could take care of that.

**Comment by philips** [comment]
Closing this since https://github.com/appc/spec/pull/70/files is ready to merge and the implementation works in rkt: https://github.com/coreos/rocket/pull/316
