### ISSUE TITLE
Define a default capability set for apps

### ISSUE THREAD

**Issue by alban** [appc/spec#598]
appc/spec defines the following [Linux isolators](https://github.com/appc/spec/blob/master/spec/ace.md#linux-isolators):
- os/linux/capabilities-remove-set: list of capabilities that will be removed from the process's capabilities bounding set, all others will be included
- os/linux/capabilities-retain-set: list of capabilities that will be retained in the process's capabilities bounding set, all others will be removed

This implicitly refers to a default set of capabilities that is not clearly defined. For example, if an application wants CAP_SETUID, should the ACI author add it in the retain set? This is actually not necessary, rkt gives CAP_SETUID by default. Docker does the same. But if an application wants to have CAP_NET_ADMIN, the ACI author must add it in the retain set because it is not in the default capability set (neither in rkt or Docker).

When the default set of capabilities is not defined, ACI authors don't know what they should write in the ACI manifest.

The spec should define something like the following:

```
        // appDefaultCapabilities defines a restricted set of capabilities given to
        // apps by default.
        appDefaultCapabilities, _ = types.NewLinuxCapabilitiesRetainSet([]string{
                "CAP_AUDIT_WRITE",
                "CAP_CHOWN",
                "CAP_DAC_OVERRIDE",
                "CAP_FSETID",
                "CAP_FOWNER",
                "CAP_KILL",
                "CAP_MKNOD",
                "CAP_NET_RAW",
                "CAP_NET_BIND_SERVICE",
                "CAP_SETUID",
                "CAP_SETGID",
                "CAP_SETPCAP",
                "CAP_SETFCAP",
                "CAP_SYS_CHROOT",
        }...)
```

(coming from https://github.com/coreos/rkt/pull/2493)

**Comment by jonboulle** [comment]
wanna put up a PR?

**Comment by alban** [comment]
Yes: https://github.com/appc/spec/pull/600
