### ISSUE TITLE
spec: discovery URIs are vague as to required variables

### ISSUE THREAD

**Issue by tdavis** [appc/spec#610]
The discovery spec states how URI templates must be interpolated:

> MUST perform a simple template substitution to determine the URL at which the resource can be retrieved ... where *name*, *version*, *os*, and *arch* are set to their respective values for the image...

The specification is vague on whether or not those particular variables are required in the template; aside from *name* they are optional labels for a manifest. It also doesn't specify whether or not other arbitrary labels may be used in the template.

**Comment by jonboulle** [comment]
See #596

**Comment by tdavis** [comment]
Closing as duplicate of #596, thanks for the link!
