### ISSUE TITLE
Make gid optional?

### ISSUE THREAD

**Issue by yifan-gu** [appc/spec#623]
Today for docker images, if the gid is missing, docker will read /etc/passwd to determine the gid.

See:
https://github.com/docker/docker/blob/266c40087cbdd80b93e435284264db5f881a03e1/daemon/oci_linux.go#L143
https://github.com/docker/docker/blob/266c40087cbdd80b93e435284264db5f881a03e1/daemon/oci_linux.go#L161
https://github.com/docker/docker/blob/4a7bd7eaef0038b006cf23adface84081e5aab3b/vendor/src/github.com/opencontainers/runc/libcontainer/user/user.go#L240

However, since appc requires gid to be non-empty, so if the gid is empty, we have to error out in rktnetes.

cc @philips @jonboulle @iaguis @alban

**Comment by philips** [comment]
What should we default it to if optional? @yifan-gu

**Comment by philips** [comment]
Maybe have docker2aci do the reading of the /etc/passwd instead in this case?

**Comment by philips** [comment]
@dgonyeo thoughts on having docker2aci reading the /etc/passwd?

**Comment by euank** [comment]
I think the best option is one of the following:

1) docker2aci reads `/etc/passwd` and sets this during conversion and, if User is set and it can't find an entry, errors out (docker errors out at runtime in that case btw). gid does not need to be optional in that case.
2) gid is optional and rkt stage1 must figure out how to default it at runtime. The stage1 can decide to read `/etc/passwd` or to just set it to 0 and/or error out as appropriate.

I think the former is the simpler option, and the latter option could still be taken in the future if desired.

**Comment by yifan-gu** [comment]
@euank +1 on the first option. I filed an issue against docker2aci. We can close this if we all agree that's the better solution.

**Comment by dgonyeo** [comment]
+1 on the first option.

**Comment by yifan-gu** [comment]
Close in favor of https://github.com/appc/docker2aci/issues/175
