### ISSUE TITLE
address-of operator removal seems to cause problems

### ISSUE THREAD

**Issue by btipling** [appc/spec#624]
Try out the instructions here:

https://coreos.com/rkt/docs/latest/trying-out-rkt.html

```
git clone https://github.com/coreos/rkt
cd rkt
vagrant up
```

I'm on OS X 10.11.5 with VirtualBox Version 5.0.20 r106931

Get this error when trying the above for rkt, seems to be in appc/spec:

```
default: # github.com/appc/spec/schema/types
==> default: /root/.gopath/src/github.com/appc/spec/schema/types/isolator_resources.go:158: cannot use req (type resource.Quantity) as type *resource.Quantity in field value
==> default: /root/.gopath/src/github.com/appc/spec/schema/types/isolator_resources.go:159: cannot use lim (type resource.Quantity) as type *resource.Quantity in field value
==> default: /root/.gopath/src/github.com/appc/spec/schema/types/isolator_resources.go:212: cannot use req (type resource.Quantity) as type *resource.Quantity in field value
==> default: /root/.gopath/src/github.com/appc/spec/schema/types/isolator_resources.go:213: cannot use lim (type resource.Quantity) as type *resource.Quantity in field value
```

This change here I think was the cause:

https://github.com/appc/spec/commit/7da0fdd4dfce6fda81869ac6ecd6ef42247957ea#diff-4667d44e5d7cf5f764587945de56685cL158

I can open the issue in coreos/rkt too if you think I should.

Full log:

https://gist.github.com/btipling/c1797dbd917b863a40ec69280ba958be

**Comment by btipling** [comment]
I added an issue on rkt as well: https://github.com/coreos/rkt/issues/2789

**Comment by jonboulle** [comment]
this should be resolved now
