### ISSUE TITLE
allow ports to be included in an image name

### ISSUE THREAD

**Issue by dgonyeo** [appc/spec#628]
An issue (https://github.com/appc/acpush/issues/6) was recently filed against acpush where the user wished to set the image name to refer to a non-default port on a host (e.g. `aci-serv:3000/tester`). Right now the `:` character is not allowed in image names, and allowing it would make version parsing a little more complicated. Is this something that should be fixed?

**Comment by jonboulle** [comment]
This would couple name to transport which is pretty much directly against the intentions of the spec. Why can't we use a flag for ports?

**Comment by jonboulle** [comment]
Danced around in https://github.com/appc/spec/pull/110

**Comment by dgonyeo** [comment]
Yup, looks like that would solve this. I can add a port flag to acpush once that gets merged.

Although on the subject of coupling name to transport, I thought rkt already complained if the image name didn't match where it pulled the image from? As in, if I `rkt fetch coreos.com/etcd` and the image manifest it gets back has the name `quay.io/coreos/etcd`, that rkt would error out?

**Comment by jonboulle** [comment]
That's not coupling to a particular transport mechanism per se - rather, it's ensuring the way the image is referenced matches what the contents are.  I admit that this is a little blurry and something abd was trying to make much more specific.
