### ISSUE TITLE
k8s.io/kubernetes/pkg/api/resource is going to move, cyclic dependency

### ISSUE THREAD

**Issue by sttts** [appc/spec#683]
.... to `k8s.io/apimachinery/pkg/api/resource`. But as Kubernetes vendors `appc/spec`, we have a cyclic dependency problem: 

- We have to update `appc/spec` in order to do the move (otherwise Kubernetes will not compile).
- But for `appc/spec` to update, we need it in `k8s.io/apimachinery`.

A solution might be to make a copy of the `Quantity` type here, cutting off the dependency.

**Comment by lucab** [comment]
Yes, I agree on cutting off the dependency. This is giving us issues in other places down the chain due to overly broad un-pinned dependencies, like in https://github.com/appc/docker2aci/pull/238.

**Comment by s-urbaniak** [comment]
I am fine with cutting the dependency. I made a quick scan over rkt and it seems we don't reference this type directly in rkt, so there should be no change necessary there.

**Comment by lucab** [comment]
I think we consume it for isolators-related logic in docker2aci (still), and for rkt we used consume more things re-exported more here. https://github.com/appc/spec/pull/672 has some history and references.

@sttts @dgonyeo who wants to cut it?

**Comment by sttts** [comment]
@lucab just go ahead cutting it. For the moment I leave pkg/api/resource in the kube repo as a temporary copy such that you have time to cut the link. Would be great if you can manage to do that in a few-days timeframe.

**Comment by jonboulle** [comment]
@sttts do you have time to put up a PR?

Dr. Stefan Schimanski <notifications@github.com> schrieb am Mi., 25. Jan.
2017, 16:04:

**Comment by sttts** [comment]
@jonboulle I can create a minimal PR switching to apimachinery once that merged in kube.

If you want to get rid of the dependency completely, some duplication of the kube code is necessary. As the type `Quantity` (that is used here) has some more deps to kubernetes, you have to see what you really need for your context.
