### ISSUE TITLE
ContainerRuntimeManifests "apps"

### ISSUE THREAD

**Issue by wereHamster** [appc/spec#72]
The items in the `ContainerRuntimeManifest` `apps` list refer to images. The `app` key in the `ImageManifest` is optional. What should be the behavior when the image has no `app` defined?

**Comment by philips** [comment]
I don't think I quite follow but I can take a shot:

If an app field is undefined and a user tries to run it with something like `rkt run example.com/no-app.aci` then the executor should fail.

**Comment by wereHamster** [comment]
So it's like there are two subtypes of an image. One whose `ImageManifest` has the `app` key present and which can be referenced by a `ContainerRuntimeManifest`, and another one without the `app` key which can only be used in a image dependency.

**Comment by jonboulle** [comment]
@wereHamster Yes, exactly. If you can think of a way to change the wording to make this clearer please feel free to submit a PR.

**Comment by philips** [comment]
Since I don't think there is anything that is actionable here I am closing it out. Feel free to re-open if you wish.
