### ISSUE TITLE
spec: HTTP Redirection during image discovery?

### ISSUE THREAD

**Issue by cnelson** [appc/spec#97]
The discovery spec says:

> If the first attempt at fetching the discovery URL returns a status code other than 200 OK or does not   contain any ac-discovery meta tags then the next higher path in the name should be tried.

I think the spec should specifically state what it does if it receives a 3xx response.

I'd vote for following redirects as while good URLs should work forever, we all know that's not how the real world works.

**Comment by kelseyhightower** [comment]
@cnelson Agreed. We have a couple of TODO's in rocket on supporting redirects. We should make it clear in the spec that redirects should be followed.
